# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "juggernaut-client"
  s.version = "2.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw", "Dave Steinberg"]
  s.date = "2013-05-30"
  s.description = "Use Juggernaut to easily implement realtime chat, collaboration, gaming and much more!"
  s.email = "dave@redterror.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/juggernaut_observer.js",
    "examples/juggernaut_observer.rb",
    "examples/roster.rb",
    "juggernaut.gemspec",
    "lib/juggernaut.rb",
    "lib/juggernaut/rails/engine.rb",
    "vendor/assets/javascripts/juggernaut-client.js"
  ]
  s.homepage = "https://github.com/redterror/juggernaut-client"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple realtime push"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
  end
end

